### ISSUE TITLE
Issue with Blender 3.2.1

### ISSUE THREAD

**Issue by Leevy27** [AlanWatton/Blender-Smooth-Meshes-Add-On#1]
Hi Alan,
Downloaded and installed your addon, activated, saved config but the Menu entry does not appear.
You can find a screenshot here in the screenshot.

Any ideas why this happen? Can I provide you more information?
Thanks, Lecra
![2022-08-05 09_38_33-Blender](https://user-images.githubusercontent.com/37998983/183027942-b957e9b3-1c95-4bf3-add0-b4ef1869087b.png)

**Comment by Leevy27** [comment]
BTW, I realized that it is not working in Blender 3.1.2 too.

**Comment by AlanWatton** [comment]
Hello, I made it in version 3.2.1 and just tried in 2.93.1, it worked in both?

I am unable to find version 3.1.2? is it an experimental build maybe?

**Comment by Leevy27** [comment]
Hi Alan,
As already mentioned in my issue report, it does not work either in v 3.2.1. The menu entry in the add menu does not appear. 

Sent from Nine
________________________________
Von: Alan Watton ***@***.***>
Gesendet: Freitag, 5. August 2022 11:41
An: AlanWatton/Blender-Smooth-Meshes-Add-On
Cc: Leevy; Author
Betreff: Re: [AlanWatton/Blender-Smooth-Meshes-Add-On] Issue with Blender 3.2.1 (Issue #1) 

Hello, I made it in version 3.2.1 and just tried in 2.93.1, it worked in both?
I am unable to find version 3.1.2? is it an experimental build maybe?

**Comment by Leevy27** [comment]
Hi Alan,

 

I tried multiple ways to get the addon to work, but no way, except when I copy and paste the addon code in the text editor and run the script. 

Here what I did:

 

1. way

Downloaded the zip file from Github named “Blender-Smooth-Meshes-Add-On-main.zip”

Installed through Blender Settings, Addon, Install.

The addon will be copied into the AppData Roaming Folder but is not visible in the setting and therefore not working

 

2. way

Extracted the file “SmoothMeshesAddOn.zip” from the file “Blender-Smooth-Meshes-Add-On-main.zip”

Installed this file through Blender.

The file “SmoothMeshesAddOn.py” is copied to the AppData, Roaming folder

The addon is visible in the addon section of the settings and I can tick the checkbox.

In the add menu (SHIFT+A) there is no “Smooth Primitives Meshes” entry available.

 

3. way

Copied the code in the script editor and ran it three times. In the Add menu I got three entries of “Smooth Primitives Meshes”

 

It looks like the addon will be not installed in the right manner or not registered in Blender. I have no entries in the Blender console related to “Smooth Primitives Meshes”

 

If you need more infos, feel free to contact me.

 

Kind regards / Mit freundlichen Grüssen

Lenio Crameri

 ***@***.***> ***@***.***

**Comment by AlanWatton** [comment]
Thanks for taking the time to report your issue but as it's been unreplicatable across different versions of Blender in both Windows and Linux. 

I can only guess that it's a setting you have configured on your system somwhere that's causing it to fail rather than there being an issue with the add-on itself (it's very simple and not much can go wrong lol), especially when it will work when you run the script manually. I'd make sure you haven't got Windows to not allow downloaded files to be used or something similar.

I'm going to close this issue for the reasons mentioned above.
